name = "singularity"
version = "0.1.0"

description = "Singleton OTP actor registry for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jhillyerd", repo = "singularity" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"
